services:
  postgres:
    image: postgres:17-alpine
    container_name: miku-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
      POSTGRES_INITDB_ARGS: '--auth=scram-sha-256'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME} -h 127.0.0.1']
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
